#!/bin/sh
#
# Perform necessary cassandra setup steps
# after package is installed.
#

PROGNAME=`basename $0`

CHOME=/opt/cassandra/embedded/apache-cassandra

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

# Add group
if ! getent group cassandra > /dev/null; then
  groupadd -r cassandra
fi

# Add user
if ! getent passwd cassandra > /dev/null; then
  useradd -r -g cassandra -d $CHOME -s /bin/false \
     -c "Apache Cassandra Embedded" cassandra
fi

# useful symlink
ln -sf embedded/apache-cassandra/bin /opt/cassandra/bin

# Data and logs directories.
mkdir -p $CHOME/logs $CHOME/data
chown -R cassandra:cassandra $CHOME/logs $CHOME/data

# Init scripts

# Determine if I'm on RH or on Debian/Ubuntu or Systemd etc
if [ -x /bin/systemctl ]; then
  ln -sf $CHOME/tools/cassandra.service.systemd /etc/systemd/system/cassandra.service
  systemctl enable $CHOME/tools/cassandra.service
  systemctl daemon-reload

elif [ -x /sbin/chkconfig ]; then
  ln -sf $CHOME/bin/cassandra.init /etc/init.d/cassandra
  chkconfig --add cassandra

elif [ -x /usr/sbin/update-rc.d ]; then
  ln -sf $CHOME/tools/cassandra.init /etc/init.d/cassandra
  update-rc.d cassandra start 50 2 3 4 5 . stop 50 0 1 6 . >/dev/null
else
  echo "not debian/ubuntu or debian. What??"
fi

echo "Thank you for installing cassandra!"
echo "You can start it by running 'service cassandra start' - don't forget to change the cluster name in $CHOME/conf/cassandra.yaml if you wish to"

exit 0
