#!/bin/sh
#
# Perform necessary cassandra setup steps
# prior to installing package.
#

PROGNAME=`basename $0`

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

invoke-rc.d cassandra stop

exit 0
