#!/bin/sh
#
# Perform necessary cassandra setup steps
# prior to installing package.
#

PROGNAME=`basename $0`

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

service cassandra stop

# Determine if I'm on RH or on Debian/Ubuntu
if [ -x /sbin/chkconfig ]; then
  chkconfig --del cassandra
elif [ -x /usr/sbin/update-rc.d ]; then
  update-rc.d remove cassandra
else
  echo "not debian/ubuntu or debian. What??"
fi

rm -f /etc/init.d/cassandra

CHOME=`getent passwd cassandra | awk -F ':' '{ print $6; }'`
if [ ${CHOME:0:15} == "/opt/cassandra/" ]; then
  userdel -r cassandra
  groupdel cassandra
fi

exit 0
