#!/bin/bash
#
# Perform necessary cassandra removal steps
# after package is uninstalled.
#

grep patrick.viet /etc/init.d/cassandra > /dev/null 2>&1
if [ $? == 0 ]; then
  chkconfig --del cassandra
  rm -f /etc/init.d/cassandra
fi

CHOME=`getent passwd cassandra | awk -F ':' '{ print $6; }'`
if [ ${CHOME:0:15} == "/opt/cassandra/" ]; then
  userdel -r cassandra
  groupdel cassandra
fi


echo "cassandra has been uninstalled!"

exit 0
